name: CI

on:
  push:
    branches: [ main, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Generate Reports
        run: npm run report:generate

      - name: Validate Reports
        run: npm run report:validate

      - name: Build (static)
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.run_id }}
          path: |
            reports/noid_board_review.md
            reports/noid_financial.json