name: Micro Preview Check (build-only)
on:
  pull_request:
    branches: [ main, master ]
jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
