name: Vercel Preview Smoke
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      GITHUB_SHA: ${{ github.sha }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4

      # Ensure repo config is clean (prevents the mix routing props error)
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm i
      - name: Config guard
        run: |
          node scripts/enforce-vercel-config.mjs

      # Poll Vercel for the preview created by this PR/commit
      - name: Wait for Vercel preview URL
        id: wait
        run: node scripts/wait-for-vercel.mjs

      - name: Smoke: landing page
        run: |
          set -e
          URL="${{ steps.wait.outputs.preview_url }}"
          echo "Testing $URL/"
          code=$(curl -s -o /tmp/index.html -w "%{http_code}" "$URL/")
          echo "HTTP $code"
          [ "$code" = "200" ] || (echo "Landing page HTTP $code" && exit 1)
          grep -qi "<html" /tmp/index.html || (echo "No HTML rendered" && exit 1)

      - name: Smoke: /api/health
        run: |
          set -e
          URL="${{ steps.wait.outputs.preview_url }}"
          body=$(curl -s -H "Accept: application/json" "$URL/api/health")
          echo "Body: $body"
          echo "$body" | grep -q '"status"[[:space:]]*:[[:space:]]*"ok"' || (echo "/api/health not ok" && exit 1)

      - name: Comment result
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview URL: ${{ steps.wait.outputs.preview_url }}
            Status: ${{ job.status }}